#!/bin/zsh
function enable-anaconda() {
  ANA=${HOME}/anaconda3/bin
  if test ! -e $ANA; then
    echo "Anaconda not found at $ANA";
    return
  fi
  export PATH="$ANA:$PATH";
  hash -r
}

function disable-anaconda() {
  export PATH="$(echo $PATH | sed -e "s/$(echo $ANA | sed -e 's/\//\\\//g')://g")"
}

function conda() {
  enable-anaconda
  unfunction conda
  conda $@
}
