#!/bin/sh
# lazy-load nvm, when available
function enable-nvm() {
  NVM_DIR="${HOME}/.nvm"
  if test ! -d "${NVM_DIR}"; then
      if test -z "$NO_NVM_WARN"; then
          echo "nvm not found at ${HOME}/.nvm; perhaps you still need to download it?"
          echo "(set NO_NVM_WARN to anything to disable this warning)"
      fi
      return
  fi
  export NVM_DIR
  [ -s "${NVM_DIR}/nvm.sh" ] && \. "${NVM_DIR}/nvm.sh"
  NODE_VERSION="$(nvm current)"
}

# laziness doesn't seem to be necessary as of 0.34, which loads quite quickly
enable-nvm
